# Generated by Django 2.2 on 2020-06-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_topskills'),
    ]

    operations = [
        migrations.AddField(
            model_name='topskills',
            name='rate',
            field=models.CharField(default=3, max_length=1),
        ),
    ]
