# Generated by Django 2.2 on 2020-06-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='jobTitle',
            field=models.CharField(default='job title', max_length=200),
        ),
    ]
