# Generated by Django 2.2 on 2020-09-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_experience_jobtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topskills',
            old_name='name',
            new_name='skillName',
        ),
        migrations.AddField(
            model_name='experience',
            name='top_skills',
            field=models.ManyToManyField(blank=True, related_name='name', to='myapi.TopSkills'),
        ),
    ]
