# Generated by Django 2.2 on 2020-09-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_auto_20200902_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='top_skills',
            field=models.ManyToManyField(blank=True, related_name='company', to='myapi.TopSkills'),
        ),
    ]
