# Generated by Django 2.2 on 2020-09-03 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_auto_20200903_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='courseTitle',
            new_name='course',
        ),
    ]
