# Generated by Django 2.2 on 2020-09-03 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_auto_20200903_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topskills',
            name='rate',
        ),
    ]
