# Generated by Django 2.2 on 2020-09-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0011_remove_topskills_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certifications',
            name='imageName',
            field=models.CharField(default='placeholder.png', max_length=50),
        ),
    ]
